frequency: 50
two_d_mode: true
publish_tf: true

odom_frame: odom
base_link_frame: footprint
world_frame: odom

odom0: /odometry/filtered

odom0_config: [false, false, false,     # x y z --> position
              false, false, false,      #roll pitch yaw
              true, true, false,        # x_vel y_vel z_vel 
              false, false, true,        # roll_vel pitch_vel yaw_vel
              false, false, false]      # x_acc y_acc z_acc
odom0_differential: false

imu0: /imu
imu0_config: [false, false, false,     # x y z --> position
              false, false, false,      #roll pitch yaw
              false, false, false,        # x_vel y_vel z_vel 
              false, false, true,        # roll_vel pitch_vel yaw_vel
              true, false, false]      # x_acc y_acc z_acc
imu0_differential: false

odom1: /odometry/gps
odom1_config: [false, false, false,     # x y z --> position
              false, false, false,      #roll pitch yaw
              true, true, false,        # x_vel y_vel z_vel 
              false, false, true,        # roll_vel pitch_vel yaw_vel
              false, false, false]      # x_acc y_acc z_acc
odom1_differential: false



