mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  leftWheel_b_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  rightWheel_b_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}

   leftWheel_f_effort_controller:
     type: effort_controllers/JointEffortController
     joint: left_front_wheel_hinge
     pid: {p: 100.0, i: 0.1, d: 10.0}
   rightWheel_f_effort_controller:
     type: effort_controllers/JointEffortController
     joint: right_front_wheel_hinge
     pid: {p: 100.0, i: 0.1, d: 10.0}

  
#rosrun turtlesim turtle_teleop_key /turtle1/cmd_vel:=/mybot/cmd_vel   
